import React from "react";

const Logo = () => {
  return (
    <svg
      version="1.1"
      id="Layer_1"
      xmlns="http://www.w3.org/2000/svg"
      x="0px"
      y="0px"
      width="32px"
      height="31px"
      viewBox="0 0 32 31"
      enable-background="new 0 0 32 31"
    >
      {" "}
      <image
        id="image0"
        x="0"
        y="0"
        href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAfCAMAAACxiD++AAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAACHFBMVEUAAAAjTXAjTW8jTXEk
TW8jTG8iTXEiTXDygGcmUmskTXAkTXEjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAj
TXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAj
TXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAj
TXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAj
TXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAj
TXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXDy
gGfygGfygGfygGfygGcjTXAjTXAjTXAjTXDygGfygGfygGfygGcjTXAjTXAjTXDygGfygGcjTXAj
TXDygGfygGcjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXDygGfygGfygGfygGfygGcjTXDy
gGfygGfygGfygGfygGfygGcjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAjTXAj
TXAjTXAjTXDygGf///+nB/GnAAAAsXRSTlMAAAAAAAAAAAAAAAAJOHmy2Ovx17F4NwtSr+n+/eit
UAo29u/i3ePwrDMEYeHbmFo0IRw1XZvfAwV08gEkfW8CaPSzMLhjQp4VGKXmPRTBExa8Emr81iYr
+2XJ+mRtxhFYF9BHo3uEifNFut7FnAflGw3IMc8sAjRbXTIf4NkeOeP+4EH1vWVef41mX8v4TCXV
qsOaKm42/P3cMXwvVFZVLQFOjNPnBvm5P3W7XhDCig/GcXeNAAAAAWJLR0Sz2m3/fgAAAAd0SU1F
B+cCGhIwBEV44PUAAAH8SURBVCjPdZP5QxJBFMfnlaWWWXhkAqKuR2Vhgna5lUdZFhCGpCgZZidl
ZhfaYZbZqWWHplZKhx2Wad/+wmZAaJfYz09v3/vs7Mx7O4yFIKKUVamr1+jSdOkZmWtTiJYwJURZ
67L1BoQx5phy84hU9fxsSVQKCouK1xt5JG3YqDCoZNNmnjSXbimzWC3lFVuL+NO2iu0Rg3bsrOSJ
VItMYeRdu/kLaXtKwgZVVdfAULuXV5ZGNkxl+wyorJNDBu3Xw3igPmZTBw8ZYLOLHDkOAyanqi6M
hlrgiItnExrdONqkLnOWUbMZnhaeb2iF91hMWwTLqc2D4z7G2iW0Ov9bQHzlRAekk8ROAacTWTzo
DHCWmBnn7BRf8Es4n8c8uGBl8bEUIt3KOmsudmkIrg5cambddidpCJevQH9VNDbpHyrBdw226yII
9PTeEPTeDKiEW7fRd0cE/XfvhRnoUZ3i/iAeZIno4Z8Ij5RC8mPgiSyip1FhSLmAYxjPnpOmkEAt
Xgw7mKZAIy/gbluhJawk30vgVT1pCESu127o/IstjD0F792oyQhprGpReDMwPiEYn3wb+mOpe6wP
GHzXFZlB4P3UdDAYnJ768JGRb/TT5xl+d740fo3OSDmL8s6cb/zaeL/PyvFn+ENczoKfc79IY8b5
M7b5Bf9vitb/Am6AwjjiuTGIAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIzLTAyLTI2VDE3OjQ4OjA0
KzAxOjAwyXyjTgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMy0wMi0yNlQxNzo0ODowNCswMTowMLgh
G/IAAAAASUVORK5CYII="
      />
    </svg>
  );
};

export default Logo;
